
ImGui.PushStyleVar(ctx, ImGui.StyleVar_Alpha,                       1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_DisabledAlpha,               0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowPadding,               8, 8)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowRounding,              0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowBorderSize,            1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowMinSize,               32, 32)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_WindowTitleAlign,            0, 0.5)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ChildRounding,               0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ChildBorderSize,             1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_PopupRounding,               0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_PopupBorderSize,             1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_FramePadding,                4, 2)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_FrameRounding,               0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_FrameBorderSize,             1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ItemSpacing,                 8, 4)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ItemInnerSpacing,            4, 4)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_IndentSpacing,               22)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_CellPadding,                 4, 2)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ScrollbarSize,               14)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ScrollbarRounding,           0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_GrabMinSize,                 12)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_GrabRounding,                0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ImageBorderSize,             1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabRounding,                 0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabBorderSize,               1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabBarBorderSize,            1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TabBarOverlineSize,          1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TableAngledHeadersAngle,     0.401426)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TableAngledHeadersTextAlign, 0.5, 0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TreeLinesSize,               1)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_TreeLinesRounding,           0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_ButtonTextAlign,             0.5, 0.51)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_SelectableTextAlign,         0, 0)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextBorderSize,     3)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextAlign,          0, 0.5)
ImGui.PushStyleVar(ctx, ImGui.StyleVar_SeparatorTextPadding,        20, 3)

ImGui.PopStyleVar(ctx, 36)



ImGui.PushStyleColor(ctx, ImGui.Col_Text,                      0xFFFFFFFF)
ImGui.PushStyleColor(ctx, ImGui.Col_TextDisabled,              0x848484FF)
ImGui.PushStyleColor(ctx, ImGui.Col_WindowBg,                  0x242424FF)
ImGui.PushStyleColor(ctx, ImGui.Col_ChildBg,                   0x0D0D0D00)
ImGui.PushStyleColor(ctx, ImGui.Col_PopupBg,                   0x141414F0)
ImGui.PushStyleColor(ctx, ImGui.Col_Border,                    0x000000DD)
ImGui.PushStyleColor(ctx, ImGui.Col_BorderShadow,              0x00000000)
ImGui.PushStyleColor(ctx, ImGui.Col_FrameBg,                   0x0F0F0F8A)
ImGui.PushStyleColor(ctx, ImGui.Col_FrameBgHovered,            0x18181866)
ImGui.PushStyleColor(ctx, ImGui.Col_FrameBgActive,             0x272727AB)
ImGui.PushStyleColor(ctx, ImGui.Col_TitleBg,                   0x0F0F0FFF)
ImGui.PushStyleColor(ctx, ImGui.Col_TitleBgActive,             0x1D1D1DFF)
ImGui.PushStyleColor(ctx, ImGui.Col_TitleBgCollapsed,          0x00000082)
ImGui.PushStyleColor(ctx, ImGui.Col_MenuBarBg,                 0x242424FF)
ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarBg,               0x05050587)
ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrab,             0x585858FF)
ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrabHovered,      0x696969FF)
ImGui.PushStyleColor(ctx, ImGui.Col_ScrollbarGrabActive,       0x828282FF)
ImGui.PushStyleColor(ctx, ImGui.Col_CheckMark,                 0x42FAAAFF)
ImGui.PushStyleColor(ctx, ImGui.Col_SliderGrab,                0x00FFA7FF)
ImGui.PushStyleColor(ctx, ImGui.Col_SliderGrabActive,          0xFC3737FF)
ImGui.PushStyleColor(ctx, ImGui.Col_Button,                    0x0B0B0B66)
ImGui.PushStyleColor(ctx, ImGui.Col_ButtonHovered,             0x343434FF)
ImGui.PushStyleColor(ctx, ImGui.Col_ButtonActive,              0x2E2E2EFF)
ImGui.PushStyleColor(ctx, ImGui.Col_Header,                    0x0000004F)
ImGui.PushStyleColor(ctx, ImGui.Col_HeaderHovered,             0x008F6FCC)
ImGui.PushStyleColor(ctx, ImGui.Col_HeaderActive,              0x42FAD6FF)
ImGui.PushStyleColor(ctx, ImGui.Col_Separator,                 0x6E6E8080)
ImGui.PushStyleColor(ctx, ImGui.Col_SeparatorHovered,          0x1ABF9FC7)
ImGui.PushStyleColor(ctx, ImGui.Col_SeparatorActive,           0x1ABF9AFF)
ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGrip,                0x35353533)
ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGripHovered,         0x262626AB)
ImGui.PushStyleColor(ctx, ImGui.Col_ResizeGripActive,          0x202020F2)
ImGui.PushStyleColor(ctx, ImGui.Col_InputTextCursor,           0xFFFFFFFF)
ImGui.PushStyleColor(ctx, ImGui.Col_TabHovered,                0x42FA8FCC)
ImGui.PushStyleColor(ctx, ImGui.Col_Tab,                       0x000000DC)
ImGui.PushStyleColor(ctx, ImGui.Col_TabSelected,               0x181818FF)
ImGui.PushStyleColor(ctx, ImGui.Col_TabSelectedOverline,       0x272727FF)
ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmed,                 0x11261FF8)
ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmedSelected,         0x236C42FF)
ImGui.PushStyleColor(ctx, ImGui.Col_TabDimmedSelectedOverline, 0x80808000)
ImGui.PushStyleColor(ctx, ImGui.Col_DockingPreview,            0x42FAAAB3)
ImGui.PushStyleColor(ctx, ImGui.Col_DockingEmptyBg,            0x333333FF)
ImGui.PushStyleColor(ctx, ImGui.Col_PlotLines,                 0x9C9C9CFF)
ImGui.PushStyleColor(ctx, ImGui.Col_PlotLinesHovered,          0xFF6E59FF)
ImGui.PushStyleColor(ctx, ImGui.Col_PlotHistogram,             0xE6B300FF)
ImGui.PushStyleColor(ctx, ImGui.Col_PlotHistogramHovered,      0xFF9900FF)
ImGui.PushStyleColor(ctx, ImGui.Col_TableHeaderBg,             0x0B0B0BFF)
ImGui.PushStyleColor(ctx, ImGui.Col_TableBorderStrong,         0x000000FF)
ImGui.PushStyleColor(ctx, ImGui.Col_TableBorderLight,          0x121212FF)
ImGui.PushStyleColor(ctx, ImGui.Col_TableRowBg,                0x0000000A)
ImGui.PushStyleColor(ctx, ImGui.Col_TableRowBgAlt,             0xB0B0B00F)
ImGui.PushStyleColor(ctx, ImGui.Col_TextLink,                  0x42FA9FFF)
ImGui.PushStyleColor(ctx, ImGui.Col_TextSelectedBg,            0x42FA8F59)
ImGui.PushStyleColor(ctx, ImGui.Col_TreeLines,                 0x6E6E8080)
ImGui.PushStyleColor(ctx, ImGui.Col_DragDropTarget,            0xFFFF00E6)
ImGui.PushStyleColor(ctx, ImGui.Col_NavCursor,                 0x00EB7EFF)
ImGui.PushStyleColor(ctx, ImGui.Col_NavWindowingHighlight,     0xFFFFFFB3)
ImGui.PushStyleColor(ctx, ImGui.Col_NavWindowingDimBg,         0xCCCCCC33)
ImGui.PushStyleColor(ctx, ImGui.Col_ModalWindowDimBg,          0xCCCCCC59)

ImGui.PopStyleColor(ctx, 60)

